### ISSUE TITLE
Adding Biography alexanderism55

### ISSUE THREAD

**Issue by alexanderism55** [lab-brussels-1/Group-1-GitHub-Project-Management#1]

**Comment by MMikhailova** [comment]
- [ ] [repo](https://github.com/_/_)
- [ ] [many small, well-named commits](https://github.com/_/_/commits)
- [ ] a nice README
- [ ] one well-named file per person
- [ ] [one pull requests for each group member](https://github.com/_/_/pulls)
  - [ ] linting checks pass
  - [ ] code review checklist is complete
  - [ ] the reviewer merged the code
